### PR TITLE
Updated README to say the project is discontinued

### PR DESCRIPTION
**Pull request by gricey432**
Just wasted an hour writing a PR for this before finding out that it's discontinued and PRs aren't being merged. Hopefully this PR will be the exception and will get merged.

### CODE REVIEW

**Comment by gricey432** [comment]
@jshackles

**Comment by keethesh** [comment]
Fork it!

**Comment by gricey432** [comment]
@keethesh There are already a couple of great forks, but the presence of forks isn't obvious and also doesn't mean this project shouldn't mark itself correctly.

**Comment by gricey432** [comment]
@jshackles has now put something in the readme in 54c29261403d631702aefde4f7cc99057d36d7c5

**Pull request closed without merging**
