### PR TITLE
Null reference caused "Badge page didn't load"

### PR DESCRIPTION
**Pull request by treloret**
Simple null check seems to have solved it, steamLogin wasn't available

### CODE REVIEW

**Comment by treloret** [comment]
Thought this was a similar to a fix that was proposed december 2015, seems I fixed it with a less brute force approach.

**Comment by opello** [comment]
I disagree that this approach is less brute force but since @jshackles merged it I suppose that doesn't matter.  This does 2 iterations of the CookieCollection, one for each Item[String] access, while the update I made to #197 caches the Cookie to only do one lookup.

**Comment by treloret** [comment]
You're bit hung up on that 'brute force' thing, and yes yours is the optimized derivative fix from mine.

**Comment by opello** [comment]
I probably appear "hung up" because I wanted to address it in the various places the problem or fix was being discussed so that everyone that might care was aware of what was happening.

My original fix was more efficient, despite your criticism, with only one iteration of the CookieCollection.  However, a design goal may be to conceal implementation details which I think is reasonable.

I'm not sure what you mean by derivative and it seems unnecessarily pejorative.  I wouldn't have pushed it into my branch and merged the conflicts from upstream if I didn't think it was a better solution.  I really just want the best solution to be employed.

**Pull request merged**
