### PR TITLE
Add setting for select solo\many idle and idle game list on form

### LINKED ISSUE #141: Idle Option : idle one or idle many, card game or non-card game
-

### PR DESCRIPTION
**Pull request by MonkAlex**
Add setting for solo\many idle mode.
One only must be work how work 0.9 build:

Add list of games, when its idle many:

So, its can be close #141, #140, #139 

I test it, but can skip any bugs.

### CODE REVIEW

**Comment by jshackles** [comment]
In my testing, this appears to change the default behavior of Idle Master in a somewhat confusing manor.  Basically, when the option is selected to idle multiple games at once, it won't do so until all games with more than 2 hours of gameplay and card drops remaining are idled first.

While this may be preferable to some, it can make a huge difference to those that idle the most expensive cards first, as those may be without playtime and thus will be some of the last to be idled.

I'll go ahead and pull this request but I'm going to clean up some of the code to make it so that multiple games are idled first if that option is selected.  :+1:

**Comment by MonkAlex** [comment]
Users complain that the cards do not drop. For those who have a lot of games, cards will not drop for weeks. I had to remake the logic.

**Comment by jshackles** [comment]
True.  We may need to add yet another option to this section to let the user decide.

**Comment by Harg2001** [comment]
Just a comment, i had 260 game to idle 10 days ago, idling 30 at once. By running idle master 8h per day, i'm now done and i see my IM doing one game at once with drop reward in pocket :). Only some days when i buy stuff, it increase again to 4-5 idle, but only for 2h. It's acceptable.

By the way, Thanks both of you for you for your great job.

**Comment by jshackles** [comment]
There are currently 2,143 games on Steam with trading cards (150 are F2P).  Even if you owned and had card drops available in every Steam game that supported them and had 0 play time, you would still be finished in less than 6 days if you ran the program straight through.

We might add additional options for this in the future, but for now I think it'll be okay to simply give users the option of multi-idling up front or simply idling games one at a time.

**Pull request merged**
